sudo: required
addons:
  chrome: stable
language: node_js
git:
  depth: 3
node_js:
  - "10"
install:
  - bundle install --deployment --jobs=3 --retry=3 --clean --path vendor/bundle
  - npm ci
script:
  - npm test
  - npm run check-broken-links
after_success:
  - npm run coveralls
stages:
  - test
  - name: browser
    if: type = push
jobs:
  include:
    - stage: browser
      node_js: 10
      script: if ! git log --format=%B --no-merges -n 1 | grep '\[skip browser\]'; then npm run js-test-cloud; fi
cache:
  directories:
    - "$HOME/.npm"
    - vendor/bundle
notifications:
  email: false
